import assert from "node:assert/strict";
import test from "node:test";
import { parseChallenge } from "../src/challenge.js";
import { classifyConformance } from "../src/conformance.js";
import { compareField, compareTransactionEvidence } from "../src/comparison.js";
import { PAYMENT_POLICY, RunLedger, validateChallenge } from "../src/policy.js";
import { buildRequest, TEST_IDS } from "../src/requests.js";
import { compatibleEndpoints, endpointCompatible, selectMiner } from "../src/selection.js";
import { inspectUnsignedChallenge } from "../src/transport.js";
import { normalizeEvidence } from "../src/normalization.js";
import { requireExecutionEnvironment, sanitizeForOutput } from "../src/payment-adapter.js";
import type { Intent, Miner, PaymentChallenge } from "../src/types.js";

const ASSET = "0x1111111111111111111111111111111111111111";
const PAYEE = "0x2222222222222222222222222222222222222222";
const challenge = (overrides: Partial<PaymentChallenge> = {}): PaymentChallenge => ({ scheme: "exact", network: PAYMENT_POLICY.network, asset: ASSET, amount: 10_000, payTo: PAYEE, validUntil: Math.floor(Date.now() / 1000) + 300, x402Version: 2, ...overrides });
const miner = (id: string, intent: Intent, rank: number, properties: string[], required: string[] = []): Miner => ({
  id, name: `Miner ${id}`, activation_status: "active", min_price_usdc: 10_000, supported_intents: [intent],
  endpoints: [{ method: "GET", path: intent === "FRAUD_DETECTION" ? "/risk-check" : intent === "URL_SCAN" ? "/url-scan" : "/lookup", description: `${intent}. Test endpoint.` }],
  input_schema: { properties: Object.fromEntries(properties.map((key) => [key, { type: "string" }])), required }, output_schema: { properties: {} },
  scores: [{ intent_id: intent, rank, score: 1 }],
});
const selection = (intent: Intent) => selectMiner([miner("49", intent, 1, intent === "FRAUD_DETECTION" ? ["query"] : intent === "URL_SCAN" ? ["url"] : ["tx_hash", "chain"], intent === "ONCHAIN_TX_LOOKUP" ? ["tx_hash"] : [])], intent);

test("neutral selection chooses best rank", () => assert.equal(selectMiner([miner("2", "URL_SCAN", 2, ["url"]), miner("9", "URL_SCAN", 1, ["url"])], "URL_SCAN").miner.id, "9"));
test("stable numeric ID breaks a complete tie", () => assert.equal(selectMiner([miner("10", "URL_SCAN", 1, ["url"]), miner("2", "URL_SCAN", 1, ["url"])], "URL_SCAN").miner.id, "2"));
test("malformed registry is rejected", () => assert.throws(() => selectMiner({}, "URL_SCAN"), /Malformed registry/));
test("wrong network is rejected", () => assert.throws(() => validateChallenge(challenge({ network: "eip155:1" }), ASSET), /Wrong payment network/));
test("x402 version must be authoritative version 2", () => { const { x402Version: _omitted, ...missingVersion } = challenge(); assert.throws(() => validateChallenge(challenge({ x402Version: 1 }), ASSET), /version 2/); assert.throws(() => validateChallenge(missingVersion, ASSET), /version 2/); assert.equal(parseChallenge({ x402Version: 2, accepts: [challenge()] }).x402Version, 2); });
test("over-budget call is rejected", () => assert.throws(() => validateChallenge(challenge({ amount: 10_001 }), ASSET), /Per-call/));
test("cumulative budget is rejected", () => { const ledger = new RunLedger(25_000); const s = selection("FRAUD_DETECTION"); assert.throws(() => ledger.authorize(TEST_IDS.FRAUD_DETECTION, "FRAUD_DETECTION", s, challenge(), ASSET), /Cumulative/); });
test("unexpected intent/miner pair is rejected", () => assert.throws(() => new RunLedger().authorize(TEST_IDS.URL_SCAN, "URL_SCAN", selection("FRAUD_DETECTION"), challenge(), ASSET), /Unexpected selected miner/));
test("unexpected intent is rejected", () => assert.throws(() => new RunLedger().authorize(TEST_IDS.FRAUD_DETECTION, "NOT_ALLOWED" as Intent, selection("FRAUD_DETECTION"), challenge(), ASSET), /Unexpected intent/));
test("malformed challenge is rejected", () => assert.throws(() => parseChallenge({ accepts: [{}] }), /Malformed/));
test("missing payee is rejected", () => assert.throws(() => validateChallenge(challenge({ payTo: "" }), ASSET), /payee/));
test("duplicate logical test is rejected", () => { const ledger = new RunLedger(); const s = selection("FRAUD_DETECTION"); ledger.authorize(TEST_IDS.FRAUD_DETECTION, "FRAUD_DETECTION", s, challenge(), ASSET); assert.throws(() => ledger.authorize(TEST_IDS.FRAUD_DETECTION, "FRAUD_DETECTION", s, challenge(), ASSET), /Duplicate/); });
test("asset must be explicitly approved", () => assert.throws(() => validateChallenge(challenge()), /Asset approval/));
test("unexpected asset is rejected", () => assert.throws(() => validateChallenge(challenge(), "0x3333333333333333333333333333333333333333"), /Unsupported payment asset/));
test("malformed asset is rejected", () => assert.throws(() => validateChallenge(challenge({ asset: "USDC" }), ASSET), /Malformed asset/));
test("expired challenge is rejected", () => assert.throws(() => validateChallenge(challenge({ validUntil: 1 }), ASSET), /Expired/));
test("request builders match all three schema families", () => { assert.ok("query" in buildRequest("FRAUD_DETECTION", selection("FRAUD_DETECTION").miner)); assert.deepEqual(buildRequest("URL_SCAN", selection("URL_SCAN").miner), { url: "https://example.com/" }); assert.ok("tx_hash" in buildRequest("ONCHAIN_TX_LOOKUP", selection("ONCHAIN_TX_LOOKUP").miner)); });
test("on-chain request uses the schema-declared Base chain value and current public receipt", () => { const value = selection("ONCHAIN_TX_LOOKUP").miner; if (!value.input_schema?.properties?.chain) throw new Error("missing fixture chain"); value.input_schema.properties.chain.enum = ["eth", "base"];
  assert.deepEqual(buildRequest("ONCHAIN_TX_LOOKUP", value), { tx_hash: "0xcd9a4af2f822034bf8b8437815c17d3f2ae56bbee8d7444b3c12093525da1882", chain: "base" }); });
test("dry-run architecture has no signer dependency", async () => { const source = await import("node:fs/promises").then((fs) => fs.readFile(new URL("../src/cli.js", import.meta.url), "utf8")); assert.doesNotMatch(source, /wrapFetchWithPayment|privateKeyToAccount|PAYMENT-SIGNATURE/); });
test("unsigned inspection sends exactly one request and never retries with payment", async () => {
  let calls = 0;
  const mockFetch = async (_input: string | URL | Request, init?: RequestInit): Promise<Response> => {
    calls += 1;
    assert.equal(new Headers(init?.headers).has("payment-signature"), false);
    return new Response(JSON.stringify({ accepts: [challenge()] }), { status: 402, headers: { "content-type": "application/json" } });
  };
  const parsed = await inspectUnsignedChallenge("http://registry.test", selection("URL_SCAN"), { url: "https://example.com" }, mockFetch);
  assert.equal(parsed.amount, 10_000);
  assert.equal(calls, 1);
});
test("conformance helper returns only declared states", () => { assert.equal(classifyConformance({ answer: "ok" }, { required: ["answer"] }), "MATCH"); assert.equal(classifyConformance({}, { required: ["answer"] }, true), "COMPATIBLE_WITH_ADAPTER"); assert.equal(classifyConformance({ other: true }, { required: ["answer"] }), "INVALID"); });
test("missing private key fails before signer initialization", () => assert.throws(() => requireExecutionEnvironment({ EVM_NETWORK: PAYMENT_POLICY.network }, ASSET), /PRIVATE_KEY/));
test("execution environment rejects wrong network", () => assert.throws(() => requireExecutionEnvironment({ TELEGRAPH_EVM_PRIVATE_KEY: `0x${"1".repeat(64)}`, EVM_NETWORK: "eip155:1" }, ASSET), /84532/));
test("schema incompatibility excludes a miner", () => { const bad = miner("1", "FRAUD_DETECTION", 1, ["address"]); assert.throws(() => selectMiner([bad], "FRAUD_DETECTION"), /No eligible/); });
test("wrong-intent endpoint is rejected despite compatible miner schema", () => assert.equal(endpointCompatible({ method: "GET", path: "/transaction/lookup", description: "ONCHAIN_TX_LOOKUP. This is not a fraud endpoint." }, "FRAUD_DETECTION"), false));
test("same miner evaluates its explicitly associated fraud endpoint", () => { const value = miner("10002", "FRAUD_DETECTION", 1, ["query"], ["query"]); value.endpoints = [{ method: "GET", path: "/transaction/lookup", description: "ONCHAIN_TX_LOOKUP. Transaction lookup." }, { method: "GET", path: "/anomaly/check", description: "FRAUD_DETECTION. Assess a supplied query." }]; assert.equal(selectMiner([value], "FRAUD_DETECTION").endpoint.path, "/anomaly/check"); });
test("correct endpoint intent with unsatisfied required schema is rejected", () => { const value = miner("7", "FRAUD_DETECTION", 1, ["query", "address"], ["query", "address"]); assert.throws(() => selectMiner([value], "FRAUD_DETECTION"), /No eligible/); });
test("correct endpoint intent with satisfiable schema is eligible", () => assert.equal(selectMiner([miner("7", "FRAUD_DETECTION", 1, ["query"], ["query"])], "FRAUD_DETECTION").miner.id, "7"));
test("multi-endpoint compatibility does not leak between endpoints", () => { const value = miner("8", "FRAUD_DETECTION", 1, ["query"]); value.endpoints = [{ method: "GET", path: "/tx", description: "ONCHAIN_TX_LOOKUP. Lookup." }, { method: "POST", path: "/risk", description: "FRAUD_DETECTION. Assess." }]; assert.deepEqual(compatibleEndpoints(value, "FRAUD_DETECTION").map((endpoint) => endpoint.path), ["/risk"]); });
test("rank still determines winner after endpoint filtering", () => { const wrong = miner("1", "FRAUD_DETECTION", 1, ["query"]); wrong.endpoints = [{ method: "GET", path: "/tx", description: "ONCHAIN_TX_LOOKUP. Lookup." }]; const eligible = miner("2", "FRAUD_DETECTION", 2, ["query"]); assert.equal(selectMiner([wrong, eligible], "FRAUD_DETECTION").miner.id, "2"); });
test("stable endpoint tie-break is deterministic", () => { const value = miner("9", "FRAUD_DETECTION", 1, ["query"]); value.endpoints = [{ method: "POST", path: "/risk/z", description: "FRAUD_DETECTION. Z." }, { method: "GET", path: "/risk/a", description: "FRAUD_DETECTION. A." }]; assert.equal(selectMiner([value], "FRAUD_DETECTION").endpoint.path, "/risk/a"); });
test("endpoint intent logic contains no owner or miner-specific identifiers", async () => { const source = await import("node:fs/promises").then((fs) => fs.readFile(new URL("../src/selection.js", import.meta.url), "utf8")); assert.doesNotMatch(source, /DegenLens|Sigvora|10002|251/); });
test("Sigvora receives no special treatment", () => { const sigvora = miner("251", "FRAUD_DETECTION", 1, []); sigvora.name = "Sigvora"; const neutral = miner("49", "FRAUD_DETECTION", 2, ["query"]); assert.equal(selectMiner([sigvora, neutral], "FRAUD_DETECTION").miner.id, "49"); });
test("normalization preserves missing confidence", () => { const value = normalizeEvidence("FRAUD_DETECTION", selection("FRAUD_DETECTION"), { label: "review", reason: "supplied" }, "MATCH"); assert.equal("confidence" in value, false); assert.deepEqual(value.unavailableFields, ["confidence"]); });
test("fraud normalization maps live schema aliases and preserves uncertainty", () => { const value = normalizeEvidence("FRAUD_DETECTION", selection("FRAUD_DETECTION"), { verdict: "out_of_coverage", reasoning: "No supported subject was supplied.", confidence: 0, coverage_complete: false, data_source: "unavailable", risk_tier: "insufficient_data" }, "MATCH"); assert.equal(value.intent, "FRAUD_DETECTION"); if (value.intent !== "FRAUD_DETECTION") return; assert.equal(value.label, "out_of_coverage"); assert.equal(value.reason, "No supported subject was supplied."); assert.equal(value.confidence, 0); assert.deepEqual(value.uncertainty, ["coverage_incomplete", "data_source_unavailable", "insufficient_data"]); assert.deepEqual(value.unavailableFields, []); });
test("URL normalization preserves supplied live evidence", () => { const value = normalizeEvidence("URL_SCAN", selection("URL_SCAN"), { url: "https://example.com/", risk: "low", safe: true, confidence: 0.93, reachable: true, risk_score: 0.1, listings: [], host_listings: [], feeds_checked: ["URLhaus", "OpenPhish"], status_code: 200, summary: "No listed threats." }, "MATCH"); assert.equal(value.intent, "URL_SCAN"); if (value.intent !== "URL_SCAN") return; assert.equal(value.queriedUrl, "https://example.com/"); assert.equal(value.verdict, "low"); assert.equal(value.safe, true); assert.equal(value.confidence, 0.93); assert.equal(value.riskScore, 0.1); assert.deepEqual(value.threatIndicators, []); assert.deepEqual(value.sources, ["URLhaus", "OpenPhish"]); assert.equal(value.scanStatus, 200); assert.deepEqual(value.unavailableFields, []); });
test("URL normalization preserves missing evidence without manufacturing safety", () => { const value = normalizeEvidence("URL_SCAN", selection("URL_SCAN"), { unrelated: true }, "MATCH"); assert.equal(value.intent, "URL_SCAN"); if (value.intent !== "URL_SCAN") return; assert.equal("safe" in value, false); assert.equal("verdict" in value, false); assert.equal("confidence" in value, false); assert.equal("threatIndicators" in value, false); assert.deepEqual(value.unavailableFields, ["confidence", "queriedUrl", "verdict", "threatIndicators"]); });
test("malformed URL response remains invalid and unrelated fields stay excluded", () => { assert.equal(classifyConformance([], { required: ["safe"] }), "INVALID"); const value = normalizeEvidence("URL_SCAN", selection("URL_SCAN"), { label: "fraud", transactionStatus: "confirmed" }, "INVALID"); assert.equal(value.intent, "URL_SCAN"); if (value.intent !== "URL_SCAN") return; assert.equal("label" in value, false); assert.equal("transactionStatus" in value, false); });
test("normalization keeps domains distinct", () => { const value = normalizeEvidence("ONCHAIN_TX_LOOKUP", selection("ONCHAIN_TX_LOOKUP"), { status: "confirmed", block_number: 7 }, "MATCH"); assert.equal(value.intent, "ONCHAIN_TX_LOOKUP"); assert.equal("label" in value, false); });
test("on-chain normalization preserves hash block addresses and supplied facts", () => { const value = normalizeEvidence("ONCHAIN_TX_LOOKUP", selection("ONCHAIN_TX_LOOKUP"), { tx_hash: "0xabc", chain: "base", status: "confirmed", block_number: 7, block_hash: "0xdef", from: "0xfrom", to: "0xto", value_wei: "0", receipt_status: "success", confidence: 0.9 }, "MATCH"); assert.equal(value.intent, "ONCHAIN_TX_LOOKUP"); if (value.intent !== "ONCHAIN_TX_LOOKUP") return; assert.equal(value.queriedTransactionHash, "0xabc"); assert.equal(value.blockNumber, 7); assert.equal(value.from, "0xfrom"); assert.equal(value.to, "0xto"); assert.equal(value.confidence, 0.9); assert.equal("label" in value, false); });
test("on-chain normalization preserves missing fields and confidence", () => { const value = normalizeEvidence("ONCHAIN_TX_LOOKUP", selection("ONCHAIN_TX_LOOKUP"), { tx_hash: "0xabc", status: "not_found" }, "MATCH"); assert.equal("confidence" in value, false); assert.ok(value.unavailableFields.includes("blockNumber")); assert.ok(value.unavailableFields.includes("from")); assert.ok(value.unavailableFields.includes("to")); assert.deepEqual(value.uncertainty, ["transaction_not_found_by_miner"]); });
test("comparison classifies matching and conflicting fields", () => { assert.equal(compareField("0xAbC", "0xabc"), "MATCH"); assert.equal(compareField(7, 8), "MISMATCH"); });
test("comparison classifies unavailable and not-comparable fields", () => { assert.equal(compareField("known", null), "UNAVAILABLE"); assert.equal(compareField(undefined, "supplied"), "NOT_COMPARABLE"); });
test("transaction comparison reports status contradiction independently", () => { const result = compareTransactionEvidence({ hash: "0xabc", chain: "base", receiptStatus: "success" }, { tx_hash: "0xabc", chain: "base", status: "not_found" }); assert.equal(result.transactionHash, "MATCH"); assert.equal(result.chain, "MATCH"); assert.equal(result.receiptStatus, "MISMATCH"); assert.equal(result.blockNumber, "UNAVAILABLE"); });
test("sanitized output removes secrets and signatures", () => { const secret = `0x${"a".repeat(64)}`; const output = sanitizeForOutput({ privateKey: secret, "payment-signature": secret }); assert.doesNotMatch(output, new RegExp("a{64}")); assert.match(output, /redacted/); });
test("unexpected redirects are rejected before payment", async () => { const redirected = async () => new Response(null, { status: 302, headers: { location: "https://evil.invalid" } }); await assert.rejects(() => inspectUnsignedChallenge("http://registry.test", selection("URL_SCAN"), { url: "https://example.com" }, redirected), /redirect/); });
test("CLI initializes paid adapter only behind explicit execution branch", async () => { const source = await import("node:fs/promises").then((fs) => fs.readFile(new URL("../src/cli.js", import.meta.url), "utf8")); assert.match(source, /if \(values\["execute-paid"\]\)/); assert.match(source, /requireExecutionEnvironment/); });
